import React, { useState } from 'react';
import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer, 
  Cell 
} from 'recharts';
import { 
  TrendingUp, 
  Package, 
  AlertTriangle, 
  Truck, 
  ArrowUpRight, 
  ArrowDownRight,
  FileText,
  Sparkles,
  Loader2,
  X
} from 'lucide-react';
import Markdown from 'react-markdown';
import { WidgetContainer } from './WidgetContainer';
import { DistributionMap } from './DistributionMap';
import { cn, formatCompactNumber } from '../lib/utils';
import { 
  KPIData, 
  AlertMessage, 
  Depot, 
  LogisticsMetric, 
  ChartDataPoint, 
  SKUPerformance, 
  StockAlert, 
  ExpiryInventory,
  Outlet
} from '../types';

interface DashboardHomeProps {
  kpis: Record<string, KPIData>;
  systemAlerts: AlertMessage[];
  depots: Depot[];
  logisticsMetrics: LogisticsMetric[];
  productionData: ChartDataPoint[];
  skus: SKUPerformance[];
  criticalStock: StockAlert[];
  expiryInventory: ExpiryInventory[];
  outlets: Outlet[];
  visibleWidgets: string[];
  productionActiveIndex: number | null;
  setProductionActiveIndex: (index: number | null) => void;
  onSync: () => void;
  onGenerateReport: (data: any) => Promise<string>;
}

export const DashboardHome: React.FC<DashboardHomeProps> = ({
  kpis,
  systemAlerts,
  depots,
  logisticsMetrics,
  productionData,
  skus,
  criticalStock,
  expiryInventory,
  outlets,
  visibleWidgets,
  productionActiveIndex,
  setProductionActiveIndex,
  onSync,
  onGenerateReport
}) => {
  const [reportData, setReportData] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const generateReport = async () => {
    setIsGenerating(true);
    try {
      const summary = await onGenerateReport({
        kpis,
        systemAlerts,
        skus: skus.slice(0, 5),
        depots: depots.map(d => ({ name: d.name, stock: d.stock, status: d.status })),
        criticalStock: criticalStock.slice(0, 3),
        expiryInventory: expiryInventory.slice(0, 3)
      });
      setReportData(summary);
    } catch (e) {
      console.error(e);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <>
      {/* Report Modal */}
      {reportData && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-xl animate-fadeIn">
          <div className="bg-[#1C1C1E] border border-[#38383A] w-full max-w-4xl h-[80vh] rounded-[40px] shadow-[0_50px_100px_rgba(0,0,0,0.5)] flex flex-col relative overflow-hidden">
            <div className="absolute top-0 right-0 w-64 h-64 bg-[#F40009]/5 rounded-full -translate-y-32 translate-x-32 blur-3xl"></div>
            
            <div className="flex items-center justify-between p-10 border-b border-[#232326]">
              <div className="flex items-center gap-6">
                <div className="w-14 h-14 bg-[#F40009] rounded-2xl flex items-center justify-center shadow-[0_0_30px_rgba(244,0,9,0.3)]">
                  <Sparkles className="w-8 h-8 text-white" />
                </div>
                <div>
                  <h2 className="text-3xl font-logo tracking-[0.1em] text-white">AI OPERATIONAL DIAGNOSTIC</h2>
                  <p className="text-[10px] text-[#8E8E93] font-black uppercase tracking-[0.4em] mt-1">Generated by Supply Intelligence Engine v3.0</p>
                </div>
              </div>
              <button 
                onClick={() => setReportData(null)}
                className="w-12 h-12 flex items-center justify-center bg-[#0A0A0A] border border-[#232326] rounded-2xl text-[#8E8E93] hover:text-[#F40009] transition-all active:scale-90"
              >
                <X className="w-6 h-6" />
              </button>
            </div>

            <div className="flex-1 overflow-y-auto p-12 custom-scrollbar report-markdown">
              <div className="prose prose-invert max-w-none prose-p:text-[#8E8E93] prose-headings:text-white prose-strong:text-[#F40009] prose-li:text-[#8E8E93]">
                <Markdown>{reportData}</Markdown>
              </div>
            </div>

            <div className="p-8 bg-[#141416] border-t border-[#232326] flex justify-between items-center">
              <p className="text-[9px] text-[#48484A] font-black uppercase tracking-[0.3em]">CONFIDENTIAL · Coca-Cola Nigeria Internal Use Only</p>
              <button 
                onClick={() => setReportData(null)}
                className="bg-white text-black px-8 py-3 rounded-2xl font-black text-xs uppercase tracking-widest hover:bg-[#F40009] hover:text-white transition-all shadow-xl"
              >
                Acknowledge Review
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Alert Bar */}
      {visibleWidgets.includes('alerts') && (
        <div className="mb-14 bg-[#1C1C1E] border-l-4 border-[#F40009] p-5 rounded-2xl flex flex-wrap items-center justify-between gap-8 shadow-xl animate-fadeIn">
          <div className="flex flex-wrap items-center gap-8">
            {systemAlerts.map(alert => (
              <div key={alert.id} className="flex items-center gap-2">
                <AlertTriangle className={cn("w-4 h-4", alert.type === 'critical' ? 'text-[#F40009]' : 'text-amber-500')} />
                <span className="text-xs font-bold text-white tracking-tight">{alert.text}</span>
              </div>
            ))}
          </div>
          <div className="flex items-center gap-4">
            <button 
              onClick={generateReport}
              disabled={isGenerating}
              className="flex items-center gap-3 px-6 py-2.5 bg-[#F40009] text-white rounded-xl font-black text-[10px] uppercase tracking-widest shadow-[0_10px_20px_rgba(244,0,9,0.2)] hover:scale-105 transition-all disabled:opacity-50"
            >
              {isGenerating ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Sparkles className="w-3.5 h-3.5" />}
              AI Summary Report
            </button>
            <button 
              onClick={onSync}
              className="flex items-center gap-2 px-4 py-2 bg-[#0A0A0A] rounded-xl border border-[#232326] text-[10px] font-black text-white uppercase tracking-widest hover:border-[#F40009] transition-all group"
            >
              <TrendingUp className="w-3 h-3 group-hover:rotate-12 transition-transform" />
              Sync Data Terminals
            </button>
          </div>
        </div>
      )}

      {/* Primary KPI Grid */}
      {visibleWidgets.includes('kpis') && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-14">
          {Object.entries(kpis).map(([key, data]) => {
            const kpi = data as KPIData;
            return (
              <div key={key} className="card-clean p-6 group cursor-pointer relative overflow-hidden">
                 <div className="flex justify-between items-start mb-6">
                    <div className="p-3 bg-[#0A0A0A] rounded-xl border border-[#232326] group-hover:border-[#F40009]/30 transition-colors">
                       <Package className="w-5 h-5 text-[#F40009]" />
                    </div>
                    <div className={cn(
                      "flex items-center gap-1 text-[11px] font-black px-2 py-1 rounded-md",
                      kpi.trendDirection === 'up' ? "bg-emerald-500/10 text-emerald-500" : "bg-red-500/10 text-red-500"
                    )}>
                      {kpi.trendDirection === 'up' ? <ArrowUpRight className="w-3 h-3" /> : <ArrowDownRight className="w-3 h-3" />}
                      {kpi.trend}%
                    </div>
                 </div>
                 <p className="text-[10px] text-[#48484A] font-black uppercase tracking-[0.25em] mb-1">{kpi.label}</p>
                 <h2 className="text-3xl font-black text-white tracking-tighter leading-none">{key === 'doi' ? kpi.currentValue : key === 'volume' ? formatCompactNumber(kpi.currentValue) : kpi.currentValue}{key === 'fillRate' || key === 'stockout' || key === 'otif' ? '%' : ''}</h2>
                 <div className="absolute bottom-0 left-0 h-1 bg-[#F40009] transition-all duration-500 w-0 group-hover:w-full opacity-50"></div>
              </div>
            );
          })}
        </div>
      )}

      {/* Logistics & Transit Infrastructure */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-10 mb-14">
         {/* Regional Hub Health */}
         <div className="lg:col-span-1 space-y-10">
            {visibleWidgets.includes('depots') && (
              <WidgetContainer title="Regional Hub Health" subtitle="Live Load Scanners">
                 <div className="grid grid-cols-2 gap-4 mt-4">
                    {depots.map(depot => (
                      <div key={depot.id} className="p-5 rounded-2xl bg-[#0A0A0A] border border-[#232326] hover:border-[#F40009]/20 transition-all">
                         <div className="flex justify-between items-start mb-4">
                            <span className="text-[10px] font-black text-[#48484A] uppercase tracking-widest">{depot.name}</span>
                            <div className={cn("w-2 h-2 rounded-full", depot.status === 'optimal' ? "bg-emerald-500" : depot.status === 'low' ? "bg-amber-500" : "bg-[#F40009]")}></div>
                         </div>
                         <h4 className="text-xl font-black text-white">{formatCompactNumber(depot.stock)}</h4>
                         <p className="text-[9px] text-[#8E8E93] font-bold uppercase mt-1">Safe Capacity: 84%</p>
                      </div>
                    ))}
                 </div>
              </WidgetContainer>
            )}

            <WidgetContainer title="Logistics Diagnostic" subtitle="Real-time Efficiency Metrics">
               <div className="space-y-8 mt-6">
                  {logisticsMetrics.map((m, i) => (
                    <div key={i}>
                       <div className="flex justify-between text-[11px] font-black uppercase tracking-widest mb-3 text-[#8E8E93]">
                          <span>{m.label}</span>
                          <span className="text-white">{m.value}</span>
                       </div>
                       <div className="h-2 w-full bg-[#0A0A0A] rounded-full overflow-hidden border border-[#232326]">
                          <div 
                            className={cn("h-full rounded-full transition-all duration-1000", m.status === 'high' ? "bg-emerald-500" : m.status === 'medium' ? "bg-amber-500" : "bg-[#F40009]")}
                            style={{ width: `${m.percentage}%` }}
                          ></div>
                       </div>
                    </div>
                  ))}
               </div>
            </WidgetContainer>
         </div>

         {/* Distribution Map */}
         {visibleWidgets.includes('map') && (
           <div className="lg:col-span-2">
              <DistributionMap outlets={outlets} className="h-full min-h-[500px]" />
           </div>
         )}
      </div>

      {/* Secondary Operations Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 mb-14">
         {/* Production Chart */}
         {visibleWidgets.includes('production') && (
           <WidgetContainer 
              title="Production vs Supply" 
              subtitle="7-Day Rolling Volume (UC)"
              className="group/chart"
           >
              <div className="h-[350px] w-full mt-10">
                 <ResponsiveContainer width="100%" height="100%">
                    <BarChart 
                      data={productionData}
                      onMouseMove={(state) => {
                        if (state.activeTooltipIndex !== undefined) {
                          setProductionActiveIndex(state.activeTooltipIndex as number);
                        }
                      }}
                      onMouseLeave={() => setProductionActiveIndex(null)}
                    >
                       <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#232326" />
                       <XAxis 
                          dataKey="name" 
                          axisLine={false} 
                          tickLine={false} 
                          tick={{ fontSize: 11, fill: '#8E8E93', fontWeight: 800 }} 
                          dy={15}
                       />
                       <YAxis 
                          axisLine={false} 
                          tickLine={false} 
                          tick={{ fontSize: 10, fill: '#48484A', fontWeight: 800 }} 
                          tickFormatter={v => `${v/1000}k`}
                          dx={-10}
                       />
                       <Tooltip 
                          cursor={{ fill: '#232326', opacity: 0.4 }}
                          content={({ active, payload }) => {
                            if (active && payload && payload.length) {
                               return (
                                 <div className="bg-[#0A0A0A] border border-[#38383A] p-4 rounded-xl shadow-2xl">
                                    <p className="text-[10px] font-black text-[#8E8E93] uppercase tracking-widest mb-1">{payload[0].payload.name}</p>
                                    <p className="text-lg font-black text-white">{payload[0].value?.toLocaleString()} UC</p>
                                    <div className="mt-2 pt-2 border-t border-[#232326]">
                                       <p className="text-[9px] font-bold text-emerald-500 uppercase">Production: Optimal</p>
                                    </div>
                                  </div>
                               );
                            }
                            return null;
                          }}
                       />
                       <Bar 
                         dataKey="value" 
                         radius={[8, 8, 0, 0]} 
                         barSize={48}
                         animationDuration={1500}
                       >
                          {productionData.map((entry, index) => (
                             <Cell 
                               key={`cell-${index}`} 
                               fill={productionActiveIndex === index ? '#F40009' : index === 5 ? '#F40009' : '#232326'}
                               className="transition-all duration-300"
                               style={{ cursor: 'pointer' }}
                             />
                          ))}
                       </Bar>
                    </BarChart>
                 </ResponsiveContainer>
              </div>
              {productionActiveIndex !== null && (
                <div className="mt-6 p-4 bg-[#0A0A0A] border border-[#F40009]/20 rounded-xl animate-fadeIn">
                   <p className="text-[10px] text-[#8E8E93] font-black uppercase mb-1">Focus Point: {productionData[productionActiveIndex].name}</p>
                   <p className="text-sm font-bold text-white">Supply efficiency at {((productionData[productionActiveIndex].value / 172000) * 100).toFixed(1)}% of weekly peak</p>
                </div>
              )}
           </WidgetContainer>
         )}

         {/* SKU Strength Board */}
         {visibleWidgets.includes('performance') && (
           <WidgetContainer title="Portfolio Velocity" subtitle="SKU Strength Leaderboard">
              <div className="space-y-4 mt-8">
                 {skus.map((sku, i) => (
                    <div key={i} className="flex items-center justify-between p-4 bg-[#0A0A0A] rounded-xl border border-[#232326] group hover:border-[#F40009]/20 transition-all">
                       <div className="flex items-center gap-4">
                          <div className="w-10 h-10 rounded-xl bg-[#1C1C1E] flex items-center justify-center font-black text-[#8E8E93] group-hover:text-[#F40009] transition-colors">{i+1}</div>
                          <div>
                             <p className="text-xs font-black text-white uppercase tracking-tight">{sku.name}</p>
                             <p className="text-[10px] text-[#48484A] font-bold uppercase">{sku.sku}</p>
                          </div>
                       </div>
                       <div className="text-right">
                          <p className="text-sm font-black text-white">{sku.percentage}%</p>
                          <p className="text-[9px] text-[#8E8E93] font-bold uppercase">Market Cap</p>
                       </div>
                    </div>
                 ))}
              </div>
           </WidgetContainer>
         )}
      </div>

      {/* Critical Stock Matrix */}
      {visibleWidgets.includes('critical') && (
        <div className="grid grid-cols-1 gap-10 mb-14">
           <WidgetContainer title="Terminal Alert Matrix" subtitle="Immediate Supply Intervention Required">
              <div className="overflow-x-auto mt-8">
                 <table className="w-full text-left">
                    <thead>
                       <tr className="border-b border-[#232326] text-[11px] font-black text-[#48484A] uppercase tracking-[0.25em]">
                          <th className="pb-6 pl-6">SKU Portfolio</th>
                          <th className="pb-6">Target Depot</th>
                          <th className="pb-6">Current DOI</th>
                          <th className="pb-6">Health</th>
                          <th className="pb-6">Window</th>
                          <th className="pb-6 pr-6 text-right">Protocol</th>
                       </tr>
                    </thead>
                    <tbody className="divide-y divide-[#232326]">
                       {criticalStock.map((alert, i) => (
                         <tr key={i} className="group hover:bg-[#1C1C1E]/50 transition-colors border-b border-[#232326]">
                            <td className="py-6 pl-6 font-bold text-sm text-white group-hover:text-[#F40009] transition-colors">{alert.sku}</td>
                            <td className="py-6 text-sm text-[#8E8E93] font-medium">{alert.location}</td>
                            <td className="py-6 text-sm font-black text-white">{alert.doi} Days</td>
                            <td className="py-6">
                               <div className="flex items-center gap-3">
                                  <div className={cn("w-2.5 h-2.5 rounded-full", alert.status === 'critical' ? "bg-[#F40009]" : alert.status === 'warning' ? "bg-amber-500" : "bg-emerald-500")}></div>
                                  <span className={cn("text-[11px] font-black uppercase tracking-widest", alert.status === 'critical' ? "text-[#F40009]" : alert.status === 'warning' ? "text-amber-500" : "text-emerald-500")}>{alert.status}</span>
                               </div>
                            </td>
                            <td className={cn("py-6 text-sm font-bold", alert.daysToStockout <= 3 ? "text-[#F40009]" : "text-white")}>{alert.daysToStockout} Days</td>
                            <td className="py-6 pr-6 text-right">
                               <button className="text-[11px] font-black text-[#007AFF] uppercase tracking-widest hover:underline px-4 py-2 bg-[#0A0A0A] rounded-lg border border-[#232326] group-hover:border-[#007AFF]/30 transition-all">{alert.action}</button>
                            </td>
                         </tr>
                       ))}
                    </tbody>
                 </table>
              </div>
           </WidgetContainer>
        </div>
      )}

      {/* Near Expiry Board */}
      {visibleWidgets.includes('expiry') && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-10 mb-14">
           <div className="lg:col-span-2">
              <WidgetContainer title="Expirations & Integrity" subtitle="Inventory at risk (Next 45 Days)">
                 <div className="overflow-x-auto mt-6">
                    <table className="w-full text-left">
                       <thead>
                          <tr className="border-b border-[#232326] text-[10px] font-bold text-[#48484A] uppercase tracking-widest">
                             <th className="pb-4">SKU</th>
                             <th className="pb-4">Depot</th>
                             <th className="pb-4 text-right">Case Qty</th>
                             <th className="pb-4 text-right">Value</th>
                             <th className="pb-4 text-right">Integrity Strategy</th>
                          </tr>
                       </thead>
                       <tbody className="divide-y divide-[#232326]">
                          {expiryInventory.map((item, i) => (
                             <tr key={i} className="hover:bg-[#1C1C1E] transition-colors border-b border-[#232326]">
                                <td className="py-4 font-bold text-xs text-white">{item.sku}</td>
                                <td className="py-4 text-xs text-[#8E8E93]">{item.depot}</td>
                                <td className="py-4 text-xs font-black text-white text-right">{item.quantity.toLocaleString()}</td>
                                <td className="py-4 text-xs font-black text-amber-500 text-right">₦{item.value.toLocaleString()}</td>
                                <td className="py-4 text-right">
                                   <span className="text-[9px] font-black text-[#007AFF] uppercase tracking-widest border border-[#007AFF]/30 px-2 py-1 rounded-md">{item.action}</span>
                                </td>
                             </tr>
                          ))}
                       </tbody>
                    </table>
                 </div>
              </WidgetContainer>
           </div>
           <div className="lg:col-span-1">
              <WidgetContainer title="System Integrity" subtitle="Protocol Controls">
                 <div className="space-y-3 mt-4">
                    <div className="p-4 bg-emerald-500/10 border border-emerald-500/20 rounded-xl">
                       <h5 className="text-xs font-black text-emerald-500 uppercase mb-1">Traceability Sync: OK</h5>
                       <p className="text-[10px] text-[#48484A] leading-tight">Last block verification completed 2m ago.</p>
                    </div>
                    <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-xl">
                       <h5 className="text-xs font-black text-red-500 uppercase mb-1">Cold Chain Warning</h5>
                       <p className="text-[10px] text-[#48484A] leading-tight">Temperature variance detected in Cluster B.</p>
                    </div>
                 </div>
              </WidgetContainer>
           </div>
        </div>
      )}
    </>
  );
};
